# Generated by Django 4.1.3 on 2022-12-13 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_order_items_order_date_needed_order_item1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('item1', models.CharField(blank=True, max_length=200, null=True)),
                ('q1', models.IntegerField(blank=True, null=True)),
                ('item2', models.CharField(blank=True, max_length=200, null=True)),
                ('q2', models.IntegerField(blank=True, null=True)),
                ('item3', models.CharField(blank=True, max_length=200, null=True)),
                ('q3', models.IntegerField(blank=True, null=True)),
                ('item4', models.CharField(blank=True, max_length=200, null=True)),
                ('q4', models.IntegerField(blank=True, null=True)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_needed', models.CharField(blank=True, max_length=200, null=True)),
                ('msg', models.TextField(blank=True, max_length=1000, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
