# Generated by Django 4.1.3 on 2022-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_drink_order_drink1_order_drink2_order_drink3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drink1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drink2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drink3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drink4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qd1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qd2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qd3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qd4',
        ),
        migrations.AddField(
            model_name='order2',
            name='sos1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order2',
            name='sos2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order2',
            name='sos3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order2',
            name='sos4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
